package aggregate

import (
	"errors"
	"fmt"
	"slices"
	"time"

	"github.com/BEDOLAGA-DEV/RemnaCore/pkg/domainevent"
	"github.com/BEDOLAGA-DEV/RemnaCore/pkg/naming"
	"github.com/google/uuid"
)

var (
	// ErrEmptySubscriptionID indicates that a required subscription ID was not provided.
	ErrEmptySubscriptionID = errors.New("subscription ID is required")

	// ErrEmptyPlatformUserID indicates that a required platform user ID was not provided.
	ErrEmptyPlatformUserID = errors.New("platform user ID is required")

	// ErrInvalidPurpose indicates an unrecognized binding purpose.
	ErrInvalidPurpose = errors.New("invalid binding purpose")

	// ErrInvalidBindingTransition indicates an invalid binding state transition.
	ErrInvalidBindingTransition = errors.New("invalid binding state transition")

	// ErrNegativeTrafficLimit indicates that a traffic limit was negative.
	ErrNegativeTrafficLimit = errors.New("traffic limit must not be negative")
)

// BindingStatus represents the lifecycle state of a Remnawave binding.
type BindingStatus string

const (
	BindingPending       BindingStatus = "pending"
	BindingActive        BindingStatus = "active"
	BindingLimited       BindingStatus = "limited"
	BindingFailed        BindingStatus = "failed"
	BindingReconciling   BindingStatus = "reconciling"
	BindingDisabled      BindingStatus = "disabled"
	BindingDeprovisioned BindingStatus = "deprovisioned"
)

// bindingTransitions defines the state machine for binding status.
// Terminal state (deprovisioned) has no valid outbound transitions.
var bindingTransitions = map[BindingStatus][]BindingStatus{
	BindingPending:       {BindingActive, BindingFailed},
	BindingActive:        {BindingLimited, BindingDisabled, BindingDeprovisioned, BindingFailed},
	BindingLimited:       {BindingActive, BindingDisabled, BindingDeprovisioned, BindingFailed},
	BindingDisabled:      {BindingActive, BindingDeprovisioned},
	BindingFailed:        {BindingPending, BindingReconciling, BindingDeprovisioned},
	BindingReconciling:   {BindingFailed, BindingDeprovisioned},
	BindingDeprovisioned: {},
}

// allBindingStatuses enumerates every BindingStatus constant.
// Keep in sync with the const block above.
var allBindingStatuses = []BindingStatus{
	BindingPending, BindingActive, BindingLimited,
	BindingFailed, BindingReconciling, BindingDisabled,
	BindingDeprovisioned,
}

// ValidateBindingTransitions checks that every binding status has an entry
// in the transition map. Called from tests, not at runtime.
func ValidateBindingTransitions() error {
	for _, s := range allBindingStatuses {
		if _, ok := bindingTransitions[s]; !ok {
			return fmt.Errorf("missing transition entry for binding status: %s", s)
		}
	}
	return nil
}

// BindingPurpose describes why a Remnawave user was created.
type BindingPurpose string

const (
	PurposeBase         BindingPurpose = "base"
	PurposeGaming       BindingPurpose = "gaming"
	PurposeStreaming    BindingPurpose = "streaming"
	PurposeFamilyMember BindingPurpose = "family_member"
)

// validPurposes enumerates the recognized binding purposes.
var validPurposes = map[BindingPurpose]bool{
	PurposeBase:         true,
	PurposeGaming:       true,
	PurposeStreaming:    true,
	PurposeFamilyMember: true,
}

// RemnawaveBinding is the aggregate root linking a platform subscription to a
// Remnawave VPN user. Each subscription can have multiple bindings (base,
// gaming add-on, streaming add-on, family members).
// It embeds EventRecorder to accumulate domain events during mutations.
// Services must call DomainEvents() after persisting the aggregate to
// retrieve and publish all pending events.
//
// Concurrency safety: this aggregate relies on PostgreSQL row-level locking
// (SELECT FOR UPDATE via txmanager.RunInTx) rather than application-level
// optimistic concurrency control (version field + WHERE version = N). This
// is a deliberate architectural choice for the following reasons:
//
//   - All mutations go through MultiSubService which wraps them in RunInTx
//   - The transactional outbox pattern ensures events are atomic with state
//   - Single-writer per entity (no concurrent writes to the same binding)
//
// If the system evolves to require CQRS read models, event sourcing, or
// distributed deployment across multiple databases, add a Version int field
// and enforce it in the repository's Update method:
//
//	UPDATE multisub.bindings SET ... WHERE id = $1 AND version = $2
//
// This would also require adding version to the sqlc query and incrementing
// it in every aggregate mutation method.
type RemnawaveBinding struct {
	domainevent.EventRecorder

	ID                 string
	SubscriptionID     string
	PlatformUserID     string
	RemnawaveUUID      string // set after provisioning
	RemnawaveShortUUID string // set after provisioning
	RemnawaveUsername  string // generated by BuildUsername
	Purpose            BindingPurpose
	Status             BindingStatus
	TrafficLimitBytes  int64
	AllowedNodes       []string
	InboundTags        []string
	FailReason         string
	SyncedAt           *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// NewBinding creates a new RemnawaveBinding in the pending state.
// It uses naming.BuildRemnawaveUsername to generate a deterministic username.
// Returns an error if required fields are missing or purpose is invalid.
func NewBinding(subID, platformUserID string, purpose BindingPurpose, index int, trafficLimit int64, now time.Time) (*RemnawaveBinding, error) {
	if subID == "" {
		return nil, ErrEmptySubscriptionID
	}
	if platformUserID == "" {
		return nil, ErrEmptyPlatformUserID
	}
	if !validPurposes[purpose] {
		return nil, ErrInvalidPurpose
	}
	if trafficLimit < 0 {
		return nil, ErrNegativeTrafficLimit
	}

	return &RemnawaveBinding{
		ID:                uuid.Must(uuid.NewV7()).String(),
		SubscriptionID:    subID,
		PlatformUserID:    platformUserID,
		RemnawaveUsername: naming.BuildRemnawaveUsername(platformUserID, string(purpose), index),
		Purpose:           purpose,
		Status:            BindingPending,
		TrafficLimitBytes: trafficLimit,
		CreatedAt:         now,
		UpdatedAt:         now,
	}, nil
}

// transitionTo attempts to move the binding to the target status using the
// data-driven state machine.
func (b *RemnawaveBinding) transitionTo(target BindingStatus, now time.Time) error {
	allowed, ok := bindingTransitions[b.Status]
	if !ok {
		return ErrInvalidBindingTransition
	}
	if !slices.Contains(allowed, target) {
		return fmt.Errorf("%w: %s -> %s", ErrInvalidBindingTransition, b.Status, target)
	}
	b.Status = target
	b.UpdatedAt = now
	return nil
}

// MarkProvisioned transitions the binding from pending to active after the
// Remnawave user has been created successfully.
func (b *RemnawaveBinding) MarkProvisioned(remnawaveUUID, shortUUID string, now time.Time) error {
	if err := b.transitionTo(BindingActive, now); err != nil {
		return err
	}
	b.RemnawaveUUID = remnawaveUUID
	b.RemnawaveShortUUID = shortUUID
	b.SyncedAt = &now
	b.RecordEvent(domainevent.NewTyped(BindingProvisionedPayload{
		BindingID:      b.ID,
		SubscriptionID: b.SubscriptionID,
		RemnawaveUUID:  remnawaveUUID,
		ShortUUID:      shortUUID,
	}, now, b.ID))
	return nil
}

// MarkFailed transitions the binding to the failed state with a reason.
func (b *RemnawaveBinding) MarkFailed(reason string, now time.Time) error {
	if err := b.transitionTo(BindingFailed, now); err != nil {
		return err
	}
	b.FailReason = reason
	b.RecordEvent(domainevent.NewTyped(BindingFailedPayload{
		BindingID:      b.ID,
		SubscriptionID: b.SubscriptionID,
		Reason:         reason,
	}, now, b.ID))
	return nil
}

// Disable transitions the binding from active to disabled.
func (b *RemnawaveBinding) Disable(now time.Time) error {
	if err := b.transitionTo(BindingDisabled, now); err != nil {
		return err
	}
	b.RecordEvent(domainevent.NewTyped(BindingDisabledPayload{
		BindingID:      b.ID,
		SubscriptionID: b.SubscriptionID,
	}, now, b.ID))
	return nil
}

// Enable transitions the binding from disabled to active. Only disabled
// bindings can be re-enabled; use MarkProvisioned for pending -> active.
func (b *RemnawaveBinding) Enable(now time.Time) error {
	if b.Status != BindingDisabled {
		return fmt.Errorf("%w: Enable requires disabled, got %s", ErrInvalidBindingTransition, b.Status)
	}
	if err := b.transitionTo(BindingActive, now); err != nil {
		return err
	}
	b.RecordEvent(domainevent.NewTyped(BindingEnabledPayload{
		BindingID:      b.ID,
		SubscriptionID: b.SubscriptionID,
	}, now, b.ID))
	return nil
}

// Limit transitions the binding from active to limited when the VPN provider
// reports that traffic has been exceeded. Unlike Disable, this is an automatic
// traffic cap — the VPN provider already restricted the user, we only record
// the state change.
func (b *RemnawaveBinding) Limit(reason string, now time.Time) error {
	if b.Status != BindingActive {
		return fmt.Errorf("%w: Limit requires active, got %s", ErrInvalidBindingTransition, b.Status)
	}
	if err := b.transitionTo(BindingLimited, now); err != nil {
		return err
	}
	b.RecordEvent(domainevent.NewTyped(BindingLimitedPayload{
		BindingID:      b.ID,
		SubscriptionID: b.SubscriptionID,
		RemnawaveUUID:  b.RemnawaveUUID,
		Reason:         reason,
	}, now, b.ID))
	return nil
}

// Unlimit transitions the binding from limited back to active when the traffic
// resets or the limit is lifted by the VPN provider.
func (b *RemnawaveBinding) Unlimit(now time.Time) error {
	if b.Status != BindingLimited {
		return fmt.Errorf("%w: Unlimit requires limited, got %s", ErrInvalidBindingTransition, b.Status)
	}
	if err := b.transitionTo(BindingActive, now); err != nil {
		return err
	}
	b.RecordEvent(domainevent.NewTyped(BindingUnlimitedPayload{
		BindingID:      b.ID,
		SubscriptionID: b.SubscriptionID,
		RemnawaveUUID:  b.RemnawaveUUID,
	}, now, b.ID))
	return nil
}

// ClaimForReconciliation transitions the binding from failed to reconciling.
// This marks the binding as being actively processed by a reconciler instance,
// preventing other instances from picking it up (TOCTOU race prevention).
func (b *RemnawaveBinding) ClaimForReconciliation(now time.Time) error {
	return b.transitionTo(BindingReconciling, now)
}

// ReleaseFromReconciliation transitions the binding from reconciling back to
// failed so it can be retried by a future reconciliation pass.
func (b *RemnawaveBinding) ReleaseFromReconciliation(now time.Time) error {
	return b.transitionTo(BindingFailed, now)
}

// Deprovision transitions the binding to deprovisioned.
func (b *RemnawaveBinding) Deprovision(now time.Time) error {
	if err := b.transitionTo(BindingDeprovisioned, now); err != nil {
		return err
	}
	b.RecordEvent(domainevent.NewTyped(BindingDeprovisionedPayload{
		BindingID:      b.ID,
		SubscriptionID: b.SubscriptionID,
		RemnawaveUUID:  b.RemnawaveUUID,
	}, now, b.ID))
	return nil
}
