package aggregate

import (
	"time"

	"github.com/google/uuid"
	"github.com/BEDOLAGA-DEV/RemnaCore/pkg/naming"
)

// BindingStatus represents the lifecycle state of a Remnawave binding.
type BindingStatus string

const (
	BindingPending       BindingStatus = "pending"
	BindingActive        BindingStatus = "active"
	BindingFailed        BindingStatus = "failed"
	BindingDisabled      BindingStatus = "disabled"
	BindingDeprovisioned BindingStatus = "deprovisioned"
)

// BindingPurpose describes why a Remnawave user was created.
type BindingPurpose string

const (
	PurposeBase         BindingPurpose = "base"
	PurposeGaming       BindingPurpose = "gaming"
	PurposeStreaming    BindingPurpose = "streaming"
	PurposeFamilyMember BindingPurpose = "family_member"
)

// RemnawaveBinding is the aggregate root linking a platform subscription to a
// Remnawave VPN user. Each subscription can have multiple bindings (base,
// gaming add-on, streaming add-on, family members).
type RemnawaveBinding struct {
	ID                 string
	SubscriptionID     string
	PlatformUserID     string
	RemnawaveUUID      string // set after provisioning
	RemnawaveShortUUID string // set after provisioning
	RemnawaveUsername  string // generated by BuildUsername
	Purpose            BindingPurpose
	Status             BindingStatus
	TrafficLimitBytes  int64
	AllowedNodes       []string
	InboundTags        []string
	FailReason         string
	SyncedAt           *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// NewBinding creates a new RemnawaveBinding in the pending state.
// It uses naming.BuildRemnawaveUsername to generate a deterministic username.
func NewBinding(subID, platformUserID, purpose string, index int, trafficLimit int64, now time.Time) *RemnawaveBinding {
	return &RemnawaveBinding{
		ID:                uuid.New().String(),
		SubscriptionID:    subID,
		PlatformUserID:    platformUserID,
		RemnawaveUsername: naming.BuildRemnawaveUsername(platformUserID, purpose, index),
		Purpose:           BindingPurpose(purpose),
		Status:            BindingPending,
		TrafficLimitBytes: trafficLimit,
		CreatedAt:         now,
		UpdatedAt:         now,
	}
}

// MarkProvisioned transitions the binding from pending to active after the
// Remnawave user has been created successfully.
func (b *RemnawaveBinding) MarkProvisioned(remnawaveUUID, shortUUID string, now time.Time) {
	b.RemnawaveUUID = remnawaveUUID
	b.RemnawaveShortUUID = shortUUID
	b.Status = BindingActive
	b.UpdatedAt = now
}

// MarkFailed transitions the binding to the failed state with a reason.
func (b *RemnawaveBinding) MarkFailed(reason string, now time.Time) {
	b.Status = BindingFailed
	b.FailReason = reason
	b.UpdatedAt = now
}

// Disable transitions the binding from active to disabled.
func (b *RemnawaveBinding) Disable(now time.Time) {
	b.Status = BindingDisabled
	b.UpdatedAt = now
}

// Enable transitions the binding from disabled to active.
func (b *RemnawaveBinding) Enable(now time.Time) {
	b.Status = BindingActive
	b.UpdatedAt = now
}

// Deprovision transitions the binding to deprovisioned.
func (b *RemnawaveBinding) Deprovision(now time.Time) {
	b.Status = BindingDeprovisioned
	b.UpdatedAt = now
}
