package postgres

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/BEDOLAGA-DEV/RemnaCore/internal/adapter/postgres/gen"
	"github.com/BEDOLAGA-DEV/RemnaCore/pkg/tenantctx"
	"github.com/BEDOLAGA-DEV/RemnaCore/pkg/txmanager"
)

// txContextKey is the context key used to store a pgx.Tx inside contexts
// created by TxManager.RunInTx.
type txContextKey string

// txKey is the singleton context key for the active database transaction.
const txKey txContextKey = "pg_tx"

// TxManager implements txmanager.Runner by wrapping function calls in a
// PostgreSQL transaction. The pgx.Tx is stored in the context so that
// repositories and the outbox publisher can participate in the same
// transaction transparently via DBFromContext.
type TxManager struct {
	pool *pgxpool.Pool
}

// NewTxManager creates a TxManager backed by the given connection pool.
func NewTxManager(pool *pgxpool.Pool) *TxManager {
	return &TxManager{pool: pool}
}

// rlsTenantVariable is the PostgreSQL session variable read by row-level
// security policies. set_config with is_local=true scopes it to the current
// transaction only.
const rlsTenantVariable = "app.tenant_id"

// RunInTx executes fn within a database transaction. The transaction is
// committed if fn returns nil, rolled back otherwise. The pgx.Tx is stored in
// the context passed to fn so that any code calling DBFromContext will use the
// transaction instead of the pool.
//
// If the context carries a tenant ID (set by the TenantRLS middleware via
// tenantctx.WithTenantID), RunInTx issues set_config('app.tenant_id', ..., true)
// so that PostgreSQL row-level security policies can enforce tenant isolation
// at the database level. The setting is scoped to this transaction and
// automatically cleared on commit/rollback.
func (tm *TxManager) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	// Re-entrant: if a transaction is already active in ctx (set by an outer
	// RunInTx), join it so nested service calls participate in the SAME atomic
	// transaction rather than beginning an independent one (which would commit
	// separately and break all-or-nothing semantics).
	if _, ok := ctx.Value(txKey).(pgx.Tx); ok {
		return fn(ctx)
	}

	tx, err := tm.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}

	// Propagate tenant ID to PostgreSQL for RLS enforcement.
	if tenantID := tenantctx.TenantIDFromContext(ctx); tenantID != "" {
		if _, err := tx.Exec(ctx, "SELECT set_config($1, $2, true)", rlsTenantVariable, tenantID); err != nil {
			// Rollback is best-effort after set_config failure; the original error is more important.
			_ = tx.Rollback(ctx)
			return fmt.Errorf("set tenant for rls: %w", err)
		}
	}

	txCtx := context.WithValue(ctx, txKey, tx)

	if err := fn(txCtx); err != nil {
		// Rollback is best-effort after fn failure; the original error is more important.
		_ = tx.Rollback(ctx)
		return err
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}

	return nil
}

// DBFromContext returns the pgx.Tx from context if a transaction is active,
// otherwise returns the pool. Both *pgxpool.Pool and pgx.Tx satisfy the
// gen.DBTX interface generated by sqlc, so callers can pass the result to
// gen.New() transparently.
func DBFromContext(ctx context.Context, pool *pgxpool.Pool) gen.DBTX {
	if tx, ok := ctx.Value(txKey).(pgx.Tx); ok {
		return tx
	}
	return pool
}

// compile-time interface check
var _ txmanager.Runner = (*TxManager)(nil)
