{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "remnacore.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remnacore.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "remnacore.selectorLabels" . | nindent 6 }}
{{- end }}
