import type { Config } from "tailwindcss";

export default {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
    "../shared/{api,stores,components,lib,types,hooks}/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        surface: "var(--surface)",
        raised: "var(--raised)",
        input: "var(--input)",
        line: "var(--line)",
        accent: "var(--accent)",
        "on-accent": "var(--on-accent)",
        warn: "var(--warn)",
        danger: "var(--danger)",
        // text ramp
        t1: "var(--t1)",
        t2: "var(--t2)",
        t3: "var(--t3)",
        t4: "var(--t4)",
        t5: "var(--t5)",
        t6: "var(--t6)",
        t7: "var(--t7)",
        t8: "var(--t8)",
        // back-compat aliases so un-migrated classes still resolve to the theme
        background: "var(--bg)",
        foreground: "var(--t1)",
        card: "var(--surface)",
        "card-foreground": "var(--t1)",
        border: "var(--line)",
        ring: "var(--accent)",
        primary: { DEFAULT: "var(--accent)", foreground: "var(--on-accent)" },
        secondary: { DEFAULT: "var(--surface)", foreground: "var(--t1)" },
        muted: { DEFAULT: "var(--surface)", foreground: "var(--t4)" },
        "muted-foreground": "var(--t4)",
        accentwarn: { DEFAULT: "var(--warn)", foreground: "var(--on-accent)" },
        destructive: { DEFAULT: "var(--danger)", foreground: "var(--t1)" },
        success: { DEFAULT: "var(--accent)", foreground: "var(--on-accent)" },
        warning: { DEFAULT: "var(--warn)", foreground: "var(--on-accent)" },
        dim: "var(--t7)",
        "border-subtle": "var(--line-soft)",
      },
      borderRadius: {
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        DEFAULT: "0px",
        full: "9999px",
      },
      fontFamily: {
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        sans: ["JetBrains Mono", "ui-monospace", "monospace"],
        display: ["Space Grotesk", "JetBrains Mono", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
