package apierror

import "net/http"

// Identity error codes.
var (
	IdentityAlreadyExists         = New("IDENTITY.ALREADY_EXISTS", "identity record already exists", http.StatusConflict)
	IdentitySetupCompleted        = New("IDENTITY.SETUP_ALREADY_COMPLETED", "admin setup already completed", http.StatusConflict)
	IdentityEmailTaken            = New("IDENTITY.EMAIL_TAKEN", "email already registered", http.StatusConflict)
	IdentityInvalidCreds          = New("IDENTITY.INVALID_CREDENTIALS", "invalid email or password", http.StatusUnauthorized)
	IdentityTokenExpired          = New("IDENTITY.TOKEN_EXPIRED", "token has expired", http.StatusGone)
	IdentitySessionExpired        = New("IDENTITY.SESSION_EXPIRED", "session has expired", http.StatusUnauthorized)
	IdentityNotFound              = New("IDENTITY.NOT_FOUND", "user not found", http.StatusNotFound)
	IdentityEmailNotVerified      = New("IDENTITY.EMAIL_NOT_VERIFIED", "email not verified", http.StatusForbidden)
	IdentityPasswordTooShort      = New("IDENTITY.PASSWORD_TOO_SHORT", "password must be at least 8 characters", http.StatusUnprocessableEntity)
	IdentityPasswordTooWeak       = New("IDENTITY.PASSWORD_TOO_WEAK", "password must contain uppercase, lowercase, and digit characters", http.StatusUnprocessableEntity)
	IdentityResetExpired          = New("IDENTITY.RESET_EXPIRED", "password reset token expired", http.StatusGone)
	IdentityResetNotFound         = New("IDENTITY.RESET_NOT_FOUND", "password reset token not found", http.StatusNotFound)
	IdentityDisplayNameTooLong    = New("IDENTITY.DISPLAY_NAME_TOO_LONG", "display name exceeds maximum length", http.StatusUnprocessableEntity)
	IdentityTelegramAlreadyLinked = New("IDENTITY.TELEGRAM_ALREADY_LINKED", "telegram account already linked", http.StatusConflict)
	IdentityTelegramNotLinked     = New("IDENTITY.TELEGRAM_NOT_LINKED", "no telegram account linked", http.StatusConflict)
)

// Billing error codes.
var (
	BillingPlanAlreadyExists         = New("BILLING.PLAN_ALREADY_EXISTS", "plan already exists", http.StatusConflict)
	BillingSubscriptionAlreadyExists = New("BILLING.SUBSCRIPTION_ALREADY_EXISTS", "subscription already exists", http.StatusConflict)
	BillingInvoiceAlreadyExists      = New("BILLING.INVOICE_ALREADY_EXISTS", "invoice already exists", http.StatusConflict)
	BillingFamilyGroupAlreadyExists  = New("BILLING.FAMILY_GROUP_ALREADY_EXISTS", "family group already exists", http.StatusConflict)
	BillingPlanNotFound              = New("BILLING.PLAN_NOT_FOUND", "plan not found", http.StatusNotFound)
	BillingSubscriptionNotFound      = New("BILLING.SUBSCRIPTION_NOT_FOUND", "subscription not found", http.StatusNotFound)
	BillingInvoiceNotFound           = New("BILLING.INVOICE_NOT_FOUND", "invoice not found", http.StatusNotFound)
	BillingFamilyGroupNotFound       = New("BILLING.FAMILY_GROUP_NOT_FOUND", "family group not found", http.StatusNotFound)
	BillingInvoiceAlreadyPaid        = New("BILLING.INVOICE_ALREADY_PAID", "invoice is already paid", http.StatusConflict)
	BillingInsufficientFunds         = New("BILLING.INSUFFICIENT_FUNDS", "insufficient payment amount", http.StatusBadRequest)
	BillingCurrencyMismatch          = New("BILLING.CURRENCY_MISMATCH", "currency mismatch", http.StatusBadRequest)
	BillingAddonNotAvailable         = New("BILLING.ADDON_NOT_AVAILABLE", "addon not available for this plan", http.StatusBadRequest)
	BillingSubscriptionNotActive     = New("BILLING.SUBSCRIPTION_NOT_ACTIVE", "subscription is not active", http.StatusConflict)
	BillingNotTrialStatus            = New("BILLING.NOT_TRIAL_STATUS", "subscription is not in trial status", http.StatusConflict)
	BillingCheckoutRateLimited       = New("BILLING.CHECKOUT_RATE_LIMITED", "checkout rate limit exceeded", http.StatusTooManyRequests)
	BillingAddonAlreadyOn            = New("BILLING.ADDON_ALREADY_ON_SUBSCRIPTION", "addon already on subscription", http.StatusConflict)
	BillingAddonNotOn                = New("BILLING.ADDON_NOT_ON_SUBSCRIPTION", "addon not on subscription", http.StatusNotFound)
	BillingPlanNotActive             = New("BILLING.PLAN_NOT_ACTIVE", "plan is not active", http.StatusBadRequest)
	BillingNoPriceConfigured         = New("BILLING.NO_PRICE_CONFIGURED", "plan has no price configured", http.StatusBadRequest)
	BillingFamilyNotEnabled          = New("BILLING.FAMILY_NOT_ENABLED", "family sharing not enabled for this plan", http.StatusConflict)
	BillingPendingPlanInactive       = New("BILLING.PENDING_PLAN_INACTIVE", "pending plan is no longer active", http.StatusConflict)
	BillingSubNotActiveForInvoice    = New("BILLING.SUBSCRIPTION_NOT_ACTIVE_FOR_INVOICING", "subscription is not active for invoicing", http.StatusConflict)
	BillingCancellationBlocked       = New("BILLING.CANCELLATION_BLOCKED", "subscription cancellation blocked", http.StatusForbidden)
	BillingCheckoutBlocked           = New("BILLING.CHECKOUT_BLOCKED", "checkout blocked by plugin", http.StatusForbidden)
	BillingInvalidTransition         = New("BILLING.INVALID_TRANSITION", "invalid subscription state transition", http.StatusConflict)
	BillingMaxFamilyExceeded         = New("BILLING.MAX_FAMILY_EXCEEDED", "maximum family members exceeded", http.StatusConflict)
	BillingAlreadyMember             = New("BILLING.ALREADY_MEMBER", "user is already a member of this family group", http.StatusConflict)
	BillingCannotRemoveOwner         = New("BILLING.CANNOT_REMOVE_OWNER", "cannot remove the owner from the family group", http.StatusConflict)
	BillingMemberNotFound            = New("BILLING.MEMBER_NOT_FOUND", "member not found in family group", http.StatusNotFound)
	BillingEmptyPlanName             = New("BILLING.EMPTY_PLAN_NAME", "plan name must not be empty", http.StatusBadRequest)
	BillingBasePriceNotPositive      = New("BILLING.BASE_PRICE_NOT_POSITIVE", "base price must be positive", http.StatusBadRequest)
	BillingNoCountriesAllowed        = New("BILLING.NO_COUNTRIES_ALLOWED", "at least one country must be allowed", http.StatusBadRequest)
	BillingAddonAlreadyExists        = New("BILLING.ADDON_ALREADY_EXISTS", "addon already exists on this plan", http.StatusConflict)
	BillingAddonNotFound             = New("BILLING.ADDON_NOT_FOUND", "addon not found", http.StatusNotFound)
	BillingInvoiceRequiresItems      = New("BILLING.INVOICE_REQUIRES_LINE_ITEMS", "at least one line item is required", http.StatusBadRequest)
	BillingInvoiceMustBeDraft        = New("BILLING.INVOICE_MUST_BE_DRAFT", "invoice must be draft to mark pending", http.StatusConflict)
	BillingInvoiceMustBePending      = New("BILLING.INVOICE_MUST_BE_PENDING", "invoice must be pending to mark paid", http.StatusConflict)
	BillingInvoicePendingForFailed   = New("BILLING.INVOICE_PENDING_FOR_FAILED", "invoice must be pending to mark failed", http.StatusConflict)
	BillingInvoiceMustBePaid         = New("BILLING.INVOICE_MUST_BE_PAID", "invoice must be paid to refund", http.StatusConflict)
	BillingPlanAlreadyActive         = New("BILLING.PLAN_ALREADY_ACTIVE", "plan is already active", http.StatusConflict)
	BillingPlanAlreadyInactive       = New("BILLING.PLAN_ALREADY_INACTIVE", "plan is already inactive", http.StatusConflict)
	BillingAddonNotOnPlan            = New("BILLING.ADDON_NOT_ON_PLAN", "addon not found on plan", http.StatusNotFound)
	BillingEmptyOwnerID              = New("BILLING.EMPTY_OWNER_ID", "owner ID must not be empty", http.StatusBadRequest)
	BillingMaxMembersTooLow          = New("BILLING.MAX_MEMBERS_TOO_LOW", "max members below minimum", http.StatusBadRequest)
	BillingMaxMembersTooHigh         = New("BILLING.MAX_MEMBERS_TOO_HIGH", "max members exceeds maximum", http.StatusBadRequest)
	BillingEmptyUserID               = New("BILLING.EMPTY_USER_ID", "user ID is required", http.StatusBadRequest)
	BillingEmptyPlanID               = New("BILLING.EMPTY_PLAN_ID", "plan ID is required", http.StatusBadRequest)
	BillingEmptyInvoiceID            = New("BILLING.EMPTY_INVOICE_ID", "invoice ID is required", http.StatusBadRequest)
	BillingEmptyAddonID              = New("BILLING.EMPTY_ADDON_ID", "addon ID must not be empty", http.StatusBadRequest)
	BillingAddonNotAvailableOnPlan   = New("BILLING.ADDON_NOT_AVAILABLE_ON_PLAN", "addon is not available on this plan", http.StatusBadRequest)
	BillingMaxAddonsExceeded         = New("BILLING.MAX_ADDONS_EXCEEDED", "maximum number of addons exceeded", http.StatusConflict)
	BillingSubNotActiveForAddon      = New("BILLING.SUBSCRIPTION_NOT_ACTIVE_FOR_ADDON", "subscription must be active or trial to modify addons", http.StatusConflict)
	BillingAlreadySubscribed         = New("BILLING.ALREADY_SUBSCRIBED", "user already has an active subscription", http.StatusConflict)
	BillingCountryNotAllowed         = New("BILLING.COUNTRY_NOT_ALLOWED", "plan not available in user's country", http.StatusForbidden)
)

// MultiSub error codes.
var (
	MultiSubBindingAlreadyExists  = New("MULTISUB.BINDING_ALREADY_EXISTS", "binding already exists", http.StatusConflict)
	MultiSubBindingNotFound       = New("MULTISUB.BINDING_NOT_FOUND", "binding not found", http.StatusNotFound)
	MultiSubProvisioningFailed    = New("MULTISUB.PROVISIONING_FAILED", "provisioning failed", http.StatusInternalServerError)
	MultiSubDeprovisioningFailed  = New("MULTISUB.DEPROVISIONING_FAILED", "deprovisioning failed", http.StatusInternalServerError)
	MultiSubSyncFailed            = New("MULTISUB.SYNC_FAILED", "sync failed", http.StatusInternalServerError)
	MultiSubBindingAlreadyActive  = New("MULTISUB.BINDING_ALREADY_ACTIVE", "binding already active", http.StatusConflict)
	MultiSubRemnawaveUnavailable  = New("MULTISUB.REMNAWAVE_UNAVAILABLE", "remnawave panel unavailable", http.StatusServiceUnavailable)
	MultiSubMaxBindingsExceeded   = New("MULTISUB.MAX_BINDINGS_EXCEEDED", "maximum bindings exceeded", http.StatusConflict)
	MultiSubSagaNotFound          = New("MULTISUB.SAGA_NOT_FOUND", "saga instance not found", http.StatusNotFound)
	MultiSubSagaAlreadyExists     = New("MULTISUB.SAGA_ALREADY_EXISTS", "saga instance already exists", http.StatusConflict)
	MultiSubBindingAlreadyLimited = New("MULTISUB.BINDING_ALREADY_LIMITED", "binding is already traffic-limited", http.StatusConflict)
	MultiSubBindingNotLimited     = New("MULTISUB.BINDING_NOT_LIMITED", "binding is not traffic-limited", http.StatusConflict)
	MultiSubNoVPNPlugin           = New("MULTISUB.NO_VPN_PLUGIN", "VPN provider not configured", http.StatusServiceUnavailable)
)

// Payment error codes.
var (
	PaymentAlreadyExists   = New("PAYMENT.ALREADY_EXISTS", "payment record already exists", http.StatusConflict)
	PaymentNotFound        = New("PAYMENT.NOT_FOUND", "payment not found", http.StatusNotFound)
	PaymentWebhookNotFound = New("PAYMENT.WEBHOOK_NOT_FOUND", "webhook log not found", http.StatusNotFound)
	PaymentWebhookDup      = New("PAYMENT.WEBHOOK_DUPLICATE", "duplicate webhook already processed", http.StatusConflict)
	PaymentNoPlugin        = New("PAYMENT.NO_PLUGIN", "no payment plugin configured", http.StatusServiceUnavailable)
	PaymentFailed          = New("PAYMENT.FAILED", "payment processing failed", http.StatusBadGateway)
	PaymentVerifyFailed    = New("PAYMENT.VERIFICATION_FAILED", "webhook verification failed", http.StatusBadRequest)
	PaymentRefundFailed    = New("PAYMENT.REFUND_FAILED", "refund processing failed", http.StatusBadGateway)
	PaymentInvalidProvider = New("PAYMENT.INVALID_PROVIDER", "invalid payment provider", http.StatusBadRequest)
	PaymentMissingInvoice  = New("PAYMENT.MISSING_INVOICE_ID", "invoice ID is required", http.StatusBadRequest)
	PaymentMissingAmount   = New("PAYMENT.MISSING_AMOUNT", "payment amount must be positive", http.StatusBadRequest)
	PaymentMissingCurrency = New("PAYMENT.MISSING_CURRENCY", "currency is required", http.StatusBadRequest)
	PaymentMissingExtID    = New("PAYMENT.MISSING_EXTERNAL_ID", "external ID is required", http.StatusBadRequest)
	PaymentInvalidState    = New("PAYMENT.INVALID_STATE", "invalid payment state transition", http.StatusConflict)
)

// Reseller error codes.
var (
	ResellerNotFound                = New("RESELLER.NOT_FOUND", "reseller resource not found", http.StatusNotFound)
	ResellerTenantNotFound          = New("RESELLER.TENANT_NOT_FOUND", "tenant not found", http.StatusNotFound)
	ResellerTenantAlreadyExists     = New("RESELLER.TENANT_ALREADY_EXISTS", "tenant already exists", http.StatusConflict)
	ResellerAccountNotFound         = New("RESELLER.ACCOUNT_NOT_FOUND", "reseller account not found", http.StatusNotFound)
	ResellerAccountAlreadyExists    = New("RESELLER.ACCOUNT_ALREADY_EXISTS", "reseller account already exists", http.StatusConflict)
	ResellerCommissionNotFound      = New("RESELLER.COMMISSION_NOT_FOUND", "commission not found", http.StatusNotFound)
	ResellerCommissionAlreadyExists = New("RESELLER.COMMISSION_ALREADY_EXISTS", "commission already exists", http.StatusConflict)
	ResellerInvalidCommission       = New("RESELLER.INVALID_COMMISSION_RATE", "commission rate must be between 0 and 100", http.StatusBadRequest)
	ResellerInvalidAPIKey           = New("RESELLER.INVALID_API_KEY", "invalid API key", http.StatusUnauthorized)
	ResellerTenantInactive          = New("RESELLER.TENANT_INACTIVE", "tenant is inactive", http.StatusForbidden)
	ResellerDuplicateDomain         = New("RESELLER.DUPLICATE_DOMAIN", "domain already in use", http.StatusConflict)
)

// Plugin error codes.
var (
	PluginNotFound               = New("PLUGIN.NOT_FOUND", "plugin not found", http.StatusNotFound)
	PluginAlreadyExists          = New("PLUGIN.ALREADY_EXISTS", "plugin already exists", http.StatusConflict)
	PluginInvalidManifest        = New("PLUGIN.INVALID_MANIFEST", "invalid plugin manifest", http.StatusBadRequest)
	PluginInvalidSlug            = New("PLUGIN.INVALID_SLUG", "invalid plugin slug", http.StatusBadRequest)
	PluginNotEnabled             = New("PLUGIN.NOT_ENABLED", "plugin is not enabled", http.StatusConflict)
	PluginAlreadyEnabled         = New("PLUGIN.ALREADY_ENABLED", "plugin is already enabled", http.StatusConflict)
	PluginHookTimeout            = New("PLUGIN.HOOK_TIMEOUT", "hook execution timed out", http.StatusGatewayTimeout)
	PluginHookHalted             = New("PLUGIN.HOOK_HALTED", "hook execution halted by plugin", http.StatusBadGateway)
	PluginPermissionDenied       = New("PLUGIN.PERMISSION_DENIED", "plugin permission denied", http.StatusForbidden)
	PluginStorageQuota           = New("PLUGIN.STORAGE_QUOTA_EXCEEDED", "plugin storage quota exceeded", http.StatusInsufficientStorage)
	PluginHTTPRateLimit          = New("PLUGIN.HTTP_RATE_LIMIT_EXCEEDED", "plugin HTTP rate limit exceeded", http.StatusTooManyRequests)
	PluginInternalNetwork        = New("PLUGIN.INTERNAL_NETWORK_ACCESS", "access to internal network addresses is forbidden", http.StatusForbidden)
	PluginWASMCompileFail        = New("PLUGIN.WASM_COMPILATION_FAILED", "WASM compilation failed", http.StatusUnprocessableEntity)
	PluginNoHandler              = New("PLUGIN.NO_HANDLER_FOR_HOOK", "no plugin handler for hook", http.StatusNotFound)
	PluginSlugMismatch           = New("PLUGIN.SLUG_MISMATCH", "plugin slug mismatch during hot reload", http.StatusBadRequest)
	PluginNotRunning             = New("PLUGIN.NOT_RUNNING", "plugin is not running", http.StatusConflict)
	PluginIncompatibleSDK        = New("PLUGIN.INCOMPATIBLE_SDK", "incompatible plugin SDK version", http.StatusConflict)
	PluginDraining               = New("PLUGIN.DRAINING", "plugin is draining", http.StatusServiceUnavailable)
	PluginWASMNotFound           = New("PLUGIN.WASM_NOT_FOUND", "WASM binary not found in content store", http.StatusNotFound)
	PluginMissingConfig          = New("PLUGIN.MISSING_CONFIG", "plugin missing required configuration", http.StatusBadRequest)
	PluginCannotUninstallBuiltIn = New("PLUGIN.CANNOT_UNINSTALL_BUILTIN", "cannot uninstall built-in plugin", http.StatusForbidden)
)

// IAM (account management & RBAC) error codes.
var (
	IAMGrantNotAllowed    = New("IAM.GRANT_NOT_ALLOWED", "you may not grant that role", http.StatusForbidden)
	IAMNotPlatformAdmin   = New("IAM.NOT_PLATFORM_ADMIN", "platform admin required", http.StatusForbidden)
	IAMLastAdmin          = New("IAM.LAST_ADMIN", "cannot revoke the last platform admin", http.StatusConflict)
	IAMInvitationExpired  = New("IAM.INVITATION_EXPIRED", "invitation has expired", http.StatusGone)
	IAMInvitationNotFound = New("IAM.INVITATION_NOT_FOUND", "invitation not found", http.StatusNotFound)
	IAMEmailAlreadyUser   = New("IAM.EMAIL_ALREADY_USER", "email already belongs to a user", http.StatusConflict)
	IAMBindingNotFound    = New("IAM.BINDING_NOT_FOUND", "role binding not found", http.StatusNotFound)
)

// Routing error codes.
var (
	RoutingNoNodes = New("ROUTING.NO_NODES_AVAILABLE", "no suitable node available", http.StatusServiceUnavailable)
)

// Common error codes used across all domains.
var (
	ValidationFailed = New("COMMON.VALIDATION_ERROR", "invalid request body", http.StatusUnprocessableEntity)
	NotFound         = New("COMMON.NOT_FOUND", "resource not found", http.StatusNotFound)
	Internal         = New("COMMON.INTERNAL", "internal server error", http.StatusInternalServerError)
	BodyTooLarge     = New("COMMON.BODY_TOO_LARGE", "request body too large", http.StatusRequestEntityTooLarge)
	Unauthorized     = New("COMMON.UNAUTHORIZED", "authentication required", http.StatusUnauthorized)
	Forbidden        = New("COMMON.FORBIDDEN", "access denied", http.StatusForbidden)
	RateLimited      = New("COMMON.RATE_LIMITED", "too many requests", http.StatusTooManyRequests)
)
