#!/usr/bin/env bash
# First deploy script for RemnaCore on a clean VPS with Docker.
# Generates secrets, JWT keys, builds frontends, runs migrations, starts stack.
#
# Prerequisites: Docker, Docker Compose v2, openssl, node >= 20, pnpm
# Usage: ./scripts/first-deploy.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

ok()   { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail() { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

# ── Helper: generate random alphanumeric string ────────────────────────────
rand_secret() {
    openssl rand -base64 "$1" | tr -dc 'a-zA-Z0-9' | head -c "$1"
}

echo "=== RemnaCore First Deploy ==="
echo ""

# ── Step 1: Generate .env ──────────────────────────────────────────────────
if [ -f .env ]; then
    warn ".env already exists, skipping generation (delete it to regenerate)"
else
    PLATFORM_DB_PASSWORD="$(rand_secret 32)"
    PLATFORM_APP_DB_PASSWORD="$(rand_secret 32)"
    REMNAWAVE_DB_PASSWORD="$(rand_secret 32)"
    REMNAWAVE_WEBHOOK_SECRET="$(rand_secret 48)"
    REMNAWAVE_JWT_AUTH_SECRET="$(rand_secret 48)"
    REMNAWAVE_JWT_API_TOKENS_SECRET="$(rand_secret 48)"
    # AES-256 key for at-rest bot-token encryption: 32 raw bytes, base64-encoded
    # (the app base64-decodes it and requires exactly 32 bytes).
    SECURITY_ENCRYPTION_KEY="$(openssl rand -base64 32)"
    METRICS_PASS="$(rand_secret 24)"

    SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

    cat > .env <<EOF
# Generated by first-deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ── Platform ────────────────────────────────────────────────────────────────
PLATFORM_DB_USER=platform
PLATFORM_DB_PASSWORD=${PLATFORM_DB_PASSWORD}
PLATFORM_DB_NAME=remnacore

# Least-privilege runtime role the APP connects as (migrations still use the
# superuser above). Provisioned by scripts/provision-app-role.sh.
PLATFORM_APP_DB_USER=remnacore_app
PLATFORM_APP_DB_PASSWORD=${PLATFORM_APP_DB_PASSWORD}

LOG_LEVEL=info
LOG_FORMAT=json

# ── CORS ────────────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS=http://${SERVER_IP},http://${SERVER_IP}:8081,http://localhost

# ── Remnawave ───────────────────────────────────────────────────────────────
REMNAWAVE_DB_USER=remnawave
REMNAWAVE_DB_PASSWORD=${REMNAWAVE_DB_PASSWORD}
REMNAWAVE_DB_NAME=remnawave

# ACTION REQUIRED: set after Remnawave first login (panel UI → API tokens)
REMNAWAVE_API_TOKEN=changeme

REMNAWAVE_WEBHOOK_SECRET=${REMNAWAVE_WEBHOOK_SECRET}
REMNAWAVE_JWT_AUTH_SECRET=${REMNAWAVE_JWT_AUTH_SECRET}
REMNAWAVE_JWT_API_TOKENS_SECRET=${REMNAWAVE_JWT_API_TOKENS_SECRET}

# ── Secrets ─────────────────────────────────────────────────────────────────
SECURITY_ENCRYPTION_KEY=${SECURITY_ENCRYPTION_KEY}
METRICS_USER=metrics
METRICS_PASS=${METRICS_PASS}

SUB_PUBLIC_DOMAIN=http://${SERVER_IP}
PANEL_DOMAIN=http://${SERVER_IP}:8080
FRONT_END_DOMAIN=http://${SERVER_IP}:8080
EOF
    ok ".env generated with random secrets"
fi

# ── Step 1.5: Back-fill required secrets into an older .env ─────────────────
# Newer compose requires METRICS_PASS and SECURITY_ENCRYPTION_KEY (and the app
# runtime role password). An .env from an earlier release lacks them, which would
# make every `docker compose` command below fail on a `${VAR:?}` guard. Append
# any missing secret so re-deploys of an existing install keep working.
ensure_env() {
    local key="$1" value="$2"
    grep -q "^${key}=" .env || printf '%s=%s\n' "$key" "$value" >> .env
}
if [ -f .env ]; then
    ensure_env PLATFORM_APP_DB_USER "remnacore_app"
    ensure_env PLATFORM_APP_DB_PASSWORD "$(rand_secret 32)"
    ensure_env SECURITY_ENCRYPTION_KEY "$(openssl rand -base64 32)"
    ensure_env METRICS_USER "metrics"
    ensure_env METRICS_PASS "$(rand_secret 24)"
    ok "Required secrets present in .env"
fi

# ── Step 2: Generate JWT keys ──────────────────────────────────────────────
if [ -f keys/private.pem ] && [ -f keys/public.pem ]; then
    warn "JWT keys already exist, skipping generation"
else
    mkdir -p keys
    openssl ecparam -genkey -name prime256v1 -noout -out keys/private.pem 2>/dev/null
    openssl ec -in keys/private.pem -pubout -out keys/public.pem 2>/dev/null
    # Container runs as uid 10001 — needs read access.
    chmod 644 keys/private.pem
    chmod 644 keys/public.pem
    ok "JWT keys generated (ECDSA P-256)"
fi

# ── Step 3: Build frontends ────────────────────────────────────────────────
if [ ! -d web/cabinet/dist ] || [ ! -d web/admin/dist ]; then
    echo "Building frontends..."
    cd web
    pnpm install --frozen-lockfile
    pnpm -r build
    cd "$PROJECT_DIR"
    ok "Frontends built (cabinet + admin)"
else
    warn "Frontend dist/ directories already exist, skipping build (delete to rebuild)"
fi

# ── Step 4: Start infrastructure services ──────────────────────────────────
echo "Starting infrastructure services..."
docker compose up -d platform-db remnawave-db valkey remnawave-valkey nats

echo "Waiting for platform-db to be ready..."
RETRIES=30
until docker compose exec -T platform-db pg_isready -U platform -d remnacore > /dev/null 2>&1; do
    RETRIES=$((RETRIES - 1))
    if [ "$RETRIES" -le 0 ]; then
        fail "platform-db did not become ready within 60 seconds"
    fi
    sleep 2
done
ok "Infrastructure services started"

# ── Step 5: Apply migrations ───────────────────────────────────────────────
# Idempotent, ledger-tracked (public.schema_migrations). Applies only migrations
# not yet recorded, so new NNN_*.sql files are picked up on every (re)deploy.
# Existing databases are baselined automatically via the saga_instances sentinel.
echo "Applying migrations..."
PSQL="docker compose exec -T platform-db psql -U platform -d remnacore -v ON_ERROR_STOP=1" \
    MIGRATIONS_DIR="internal/adapter/postgres/migrations" \
    bash scripts/migrate.sh || fail "Migrations failed"
ok "Migrations applied"

# ── Step 5.5: Provision the least-privilege app DB role ────────────────────
# The app refuses to boot as a superuser/BYPASSRLS role (would void tenant RLS),
# so it connects as remnacore_app. Older .env files predate this — ensure the
# credentials exist there (compose reads them), then create/grant the role as
# the superuser BEFORE the app starts so its connection succeeds.
echo "Provisioning application database role..."
if ! grep -q '^PLATFORM_APP_DB_USER=' .env; then
    printf '\n# Least-privilege runtime role the app connects as (added by first-deploy.sh)\nPLATFORM_APP_DB_USER=remnacore_app\n' >> .env
fi
if ! grep -q '^PLATFORM_APP_DB_PASSWORD=' .env; then
    printf 'PLATFORM_APP_DB_PASSWORD=%s\n' "$(rand_secret 32)" >> .env
fi
# shellcheck disable=SC1091
APP_DB_USER="$(grep '^PLATFORM_APP_DB_USER=' .env | head -1 | cut -d= -f2-)"
APP_DB_PASSWORD="$(grep '^PLATFORM_APP_DB_PASSWORD=' .env | head -1 | cut -d= -f2-)"
PSQL="docker compose exec -T platform-db psql -U platform -d remnacore -v ON_ERROR_STOP=1" \
    APP_DB_USER="${APP_DB_USER:-remnacore_app}" \
    APP_DB_PASSWORD="$APP_DB_PASSWORD" \
    bash scripts/provision-app-role.sh || fail "Failed to provision app DB role"
ok "Application database role provisioned"

# ── Step 6: Start application services ─────────────────────────────────────
echo "Starting application services..."
docker compose up -d --build
ok "Application services started"

# ── Step 7: Health check ───────────────────────────────────────────────────
echo "Waiting for RemnaCore to be healthy..."
RETRIES=30
until curl -sf http://localhost:80/healthz > /dev/null 2>&1; do
    RETRIES=$((RETRIES - 1))
    if [ "$RETRIES" -le 0 ]; then
        fail "RemnaCore did not pass health check within 60 seconds"
    fi
    sleep 2
done
ok "Health check passed"

# The first administrator is NOT created here — open the Admin panel and the
# first-run setup wizard will prompt you to create it (POST /api/setup). The
# wizard is reachable only while no admin exists and bounces to /login after.

# ── Done ───────────────────────────────────────────────────────────────────
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

echo ""
echo -e "${GREEN}=== Deploy Complete ===${NC}"
echo ""
echo "  Cabinet:         http://${SERVER_IP}:80"
echo "  Admin:           http://${SERVER_IP}:8081"
echo "  Remnawave panel: http://${SERVER_IP}:8080"
echo "  API:             http://${SERVER_IP}:80/api"
echo "  Metrics:         http://${SERVER_IP}:80/metrics"
echo ""
echo -e "${GREEN}  First-run setup:${NC}"
echo "    Open the Admin panel and create your administrator account"
echo "    (the setup wizard appears automatically on first launch)."
echo ""
echo -e "${YELLOW}ACTION REQUIRED:${NC}"
echo "  1. Open the Admin panel at http://${SERVER_IP}:8081 and create the admin"
echo "  2. Open Remnawave panel at http://${SERVER_IP}:8080"
echo "  3. Create an API token in the Remnawave panel"
echo "  4. Edit .env and set REMNAWAVE_API_TOKEN=<your-token>"
echo "  5. Run: docker compose restart remnacore"
echo ""
echo -e "${YELLOW}RECOMMENDED:${NC} schedule database backups —"
echo "  30 3 * * * cd ${PROJECT_DIR} && ./scripts/backup.sh >> /var/log/remnacore-backup.log 2>&1"
