#!/usr/bin/env bash
# First deploy script for RemnaCore on a clean VPS with Docker.
# Generates secrets, JWT keys, builds frontends, runs migrations, starts stack.
#
# Prerequisites: Docker, Docker Compose v2, openssl, node >= 20, pnpm
# Usage: ./scripts/first-deploy.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

ok()   { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail() { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

# ── Helper: generate random alphanumeric string ────────────────────────────
rand_secret() {
    openssl rand -base64 "$1" | tr -dc 'a-zA-Z0-9' | head -c "$1"
}

echo "=== RemnaCore First Deploy ==="
echo ""

# ── Step 1: Generate .env ──────────────────────────────────────────────────
if [ -f .env ]; then
    warn ".env already exists, skipping generation (delete it to regenerate)"
else
    PLATFORM_DB_PASSWORD="$(rand_secret 32)"
    REMNAWAVE_DB_PASSWORD="$(rand_secret 32)"
    REMNAWAVE_WEBHOOK_SECRET="$(rand_secret 48)"
    REMNAWAVE_JWT_AUTH_SECRET="$(rand_secret 48)"
    REMNAWAVE_JWT_API_TOKENS_SECRET="$(rand_secret 48)"

    SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

    cat > .env <<EOF
# Generated by first-deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ── Platform ────────────────────────────────────────────────────────────────
PLATFORM_DB_USER=platform
PLATFORM_DB_PASSWORD=${PLATFORM_DB_PASSWORD}
PLATFORM_DB_NAME=remnacore

LOG_LEVEL=info
LOG_FORMAT=json

# ── CORS ────────────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS=http://${SERVER_IP},http://${SERVER_IP}:8081,http://localhost

# ── Remnawave ───────────────────────────────────────────────────────────────
REMNAWAVE_DB_USER=remnawave
REMNAWAVE_DB_PASSWORD=${REMNAWAVE_DB_PASSWORD}
REMNAWAVE_DB_NAME=remnawave

# ACTION REQUIRED: set after Remnawave first login (panel UI → API tokens)
REMNAWAVE_API_TOKEN=changeme

REMNAWAVE_WEBHOOK_SECRET=${REMNAWAVE_WEBHOOK_SECRET}
REMNAWAVE_JWT_AUTH_SECRET=${REMNAWAVE_JWT_AUTH_SECRET}
REMNAWAVE_JWT_API_TOKENS_SECRET=${REMNAWAVE_JWT_API_TOKENS_SECRET}

SUB_PUBLIC_DOMAIN=http://${SERVER_IP}
PANEL_DOMAIN=http://${SERVER_IP}:8080
FRONT_END_DOMAIN=http://${SERVER_IP}:8080
EOF
    ok ".env generated with random secrets"
fi

# ── Step 2: Generate JWT keys ──────────────────────────────────────────────
if [ -f keys/private.pem ] && [ -f keys/public.pem ]; then
    warn "JWT keys already exist, skipping generation"
else
    mkdir -p keys
    openssl ecparam -genkey -name prime256v1 -noout -out keys/private.pem 2>/dev/null
    openssl ec -in keys/private.pem -pubout -out keys/public.pem 2>/dev/null
    # Container runs as uid 10001 — needs read access.
    chmod 644 keys/private.pem
    chmod 644 keys/public.pem
    ok "JWT keys generated (ECDSA P-256)"
fi

# ── Step 3: Build frontends ────────────────────────────────────────────────
if [ ! -d web/cabinet/dist ] || [ ! -d web/admin/dist ]; then
    echo "Building frontends..."
    cd web
    pnpm install --frozen-lockfile
    pnpm -r build
    cd "$PROJECT_DIR"
    ok "Frontends built (cabinet + admin)"
else
    warn "Frontend dist/ directories already exist, skipping build (delete to rebuild)"
fi

# ── Step 4: Start infrastructure services ──────────────────────────────────
echo "Starting infrastructure services..."
docker compose up -d platform-db remnawave-db valkey remnawave-valkey nats

echo "Waiting for platform-db to be ready..."
RETRIES=30
until docker compose exec -T platform-db pg_isready -U platform -d remnacore > /dev/null 2>&1; do
    RETRIES=$((RETRIES - 1))
    if [ "$RETRIES" -le 0 ]; then
        fail "platform-db did not become ready within 60 seconds"
    fi
    sleep 2
done
ok "Infrastructure services started"

# ── Step 5: Apply migrations ───────────────────────────────────────────────
# Idempotency check: skip if the last migration's artifact exists.
MIGRATION_CHECK=$(docker compose exec -T platform-db psql \
    -U platform -d remnacore -tAc \
    "SELECT 1 FROM information_schema.tables WHERE table_schema='multisub' AND table_name='saga_instances'" 2>/dev/null || true)

if [ "$MIGRATION_CHECK" = "1" ]; then
    warn "Migrations already applied, skipping"
else
    echo "Applying migrations..."
    # Source .env for DB credentials in the psql connection.
    for migration in internal/adapter/postgres/migrations/*.sql; do
        echo "  Applying $(basename "$migration")..."
        docker compose exec -T platform-db psql -U platform -d remnacore < "$migration" > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            fail "Migration $(basename "$migration") failed"
        fi
    done
    ok "Migrations applied ($(ls -1 internal/adapter/postgres/migrations/*.sql | wc -l | tr -d ' ') files)"
fi

# ── Step 6: Start application services ─────────────────────────────────────
echo "Starting application services..."
docker compose up -d --build
ok "Application services started"

# ── Step 7: Health check ───────────────────────────────────────────────────
echo "Waiting for RemnaCore to be healthy..."
RETRIES=30
until curl -sf http://localhost:80/healthz > /dev/null 2>&1; do
    RETRIES=$((RETRIES - 1))
    if [ "$RETRIES" -le 0 ]; then
        fail "RemnaCore did not pass health check within 60 seconds"
    fi
    sleep 2
done
ok "Health check passed"

# ── Step 8: Create admin account ───────────────────────────────────────────
ADMIN_EMAIL="admin@remnacore.local"
ADMIN_CHECK=$(docker compose exec -T platform-db psql -U platform -d remnacore -tAc \
    "SELECT 1 FROM identity.platform_users WHERE email = '${ADMIN_EMAIL}'" 2>/dev/null || true)

if [ "$ADMIN_CHECK" = "1" ]; then
    warn "Admin account already exists (${ADMIN_EMAIL}), skipping"
    ADMIN_PASSWORD="<already created>"
else
    ADMIN_PASSWORD="$(rand_secret 24)"
    # Register via API
    REGISTER_RESULT=$(curl -sf -X POST http://localhost:80/api/auth/register \
        -H "Content-Type: application/json" \
        -d "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\"}" 2>/dev/null || true)

    if [ -z "$REGISTER_RESULT" ]; then
        fail "Failed to register admin account"
    fi

    # Promote to admin role
    docker compose exec -T platform-db psql -U platform -d remnacore \
        -c "UPDATE identity.platform_users SET role = 'admin', email_verified = true WHERE email = '${ADMIN_EMAIL}';" > /dev/null 2>&1

    ok "Admin account created"
fi

# ── Done ───────────────────────────────────────────────────────────────────
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

echo ""
echo -e "${GREEN}=== Deploy Complete ===${NC}"
echo ""
echo "  Cabinet:         http://${SERVER_IP}:80"
echo "  Admin:           http://${SERVER_IP}:8081"
echo "  Remnawave panel: http://${SERVER_IP}:8080"
echo "  API:             http://${SERVER_IP}:80/api"
echo "  Metrics:         http://${SERVER_IP}:80/metrics"
echo ""
if [ "$ADMIN_PASSWORD" != "<already created>" ]; then
    echo -e "${GREEN}  Admin credentials:${NC}"
    echo "    Email:    ${ADMIN_EMAIL}"
    echo "    Password: ${ADMIN_PASSWORD}"
    echo ""
    echo "  ⚠  Save these credentials — they will not be shown again."
fi
echo ""
echo -e "${YELLOW}ACTION REQUIRED:${NC}"
echo "  1. Open Remnawave panel at http://${SERVER_IP}:8080"
echo "  2. Create an API token in the panel"
echo "  3. Edit .env and set REMNAWAVE_API_TOKEN=<your-token>"
echo "  4. Run: docker compose restart remnacore"
